
export enum StageType {
  OVERVIEW = 'OVERVIEW',
  START = 'START',
  CONFRONTATION = 'CONFRONTATION',
  COLLABORATION = 'COLLABORATION',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  UPDATE = 'UPDATE',
  SETTLEMENT = 'SETTLEMENT',
  NONE = 'NONE',
}
